version: '3.8'
services:
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=passpass
    image: mysql:5.7
    networks:
      - default
    ports:
      - "3306:3306"
    restart: on-failure

  postgresql:
    environment:
      - POSTGRES_USER=migrator
      - POSTGRES_PASSWORD=passpass
    image: postgres:11.1-alpine
    networks:
      - default
    ports:
      - "5432:5432"
    restart: on-failure
