version: '3.4'
services:
  mysql:
    environment:
      - MYSQL_USER=migrator
      - MYSQL_PASSWORD=passpass
    image: woahbase/alpine-mysql:x86_64
    networks:
      - default
    ports:
      - "3306:3306"
    restart: on-failure

  postgresql:
    environment:
      - POSTGRES_USER=migrator
      - POSTGRES_PASSWORD=passpass
    image: postgres:11.1-alpine
    networks:
      - default
    ports:
      - "5432:5432"
    restart: on-failure
